theme: jekyll-theme-minimal
title: pTFCE - Probabilistic Threshold-free Cluster Enhancement of Neuroimages
description: maintained by Tamas Spisak
logo: img/sidebar_real_data2.png
show_downloads: "false"
